### ISSUE TITLE
Doesn’t install

### ISSUE THREAD

**Issue by JenniferMack** [harvesthq/harvest_for_safari#2]
Safari: Version 9.1 (11601.5.17.1)
Mac: Version 10.11.4 (15E65)

When clicking the extension, the trust box opens but when clicking “trust” nothing happens, and the extension does not appear in the extensions sidebar.

**Comment by 43north** [comment]
I also have this issue running the exact same versions of Safari and El Capitan as above.

**Comment by pusewicz** [comment]
Hi!

Sorry for the trouble!

Usually a system reboot resolves this issue! Would you mind doing that and letting me know if it worked?

This kind of issues have been know with Safari, see:
https://discussions.agilebits.com/discussion/51929/safari-extension-wont-install-on-el-capitan

**Comment by 43north** [comment]
Tried a reboot but still won't install unfortunately

**Comment by 43north** [comment]
[This solved the problem](https://discussions.apple.com/thread/7254177?tstart=0): 

> Installing safariextz files works also if you use your keyboard to confirm the Trust extension source dialog. Mouse clicking on "Trust" button doesn't work.
> 
> To install a safariextz file on OS X 10.11.1+, go to System Preferences > Keyboard > Shortcuts > Full Keyboard Access > select "All controls" option. Then double click on safariextz file and when the Trust prompt appears select the "Trust" button with your Tab key and confirm with the Space bar. This way extension installed just fine. Just don't use your mouse to click on the "Trust" button, it will not work.

**Comment by pusewicz** [comment]
@43north Thanks for the info! It is really annoying that it's not working as expected and impacts all of the Safari Extensions.

**Comment by pusewicz** [comment]
The extension is now available on the [Safari Extension Gallery](https://safari-extensions.apple.com/?q=Harvest%20Time%20Tracker) which should solve these issues.
