### ISSUE TITLE
Won't sign in

### ISSUE THREAD

**Issue by swhitlow** [harvesthq/harvest_for_safari#3]
Hello - just downloaded the latest version of this extension for Safari. I signed in and it popped up a window and then said "You’re ready to use Harvest! You can close this window now."

I close the window (tab) and then click on the Harvest icon again and it asks me to sign in again. It does this over and over again and will never allow me to sign in. I have a valid account (as I am able to successfully sign in) but it continues to ask me to sign in using the extension. 

Is there a way for me to fix this? Thanks!

**Comment by tjschuck** [comment]
Hi @swhitlow — can you please write in to support@harvestapp.com?  We'll be able to provide you with some more account-specific help there without sharing all of your details publicly here 😉 

Thanks!
