### ISSUE TITLE
Attempting to use the latest release on BigSur's Safari doesn't work

### ISSUE THREAD

**Issue by cusspvz** [harvesthq/harvest_for_safari#7]
I attempted to install the Harvest Safari extension directly from the App Store, it doens't show up there. So I found this repo and attempted to install the latest available release, but got this modal:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/3604053/104202505-ea369900-5422-11eb-8ead-5e81ed7095b5.png">

Not sure if there's an alternative way to install it or if it is really incompatible with this version of Safari.

Safari version details:
Version 14.0.2 (16610.3.7.1.9)

<img width="283" alt="image" src="https://user-images.githubusercontent.com/3604053/104202674-20741880-5423-11eb-87c5-a1dd51da0d03.png">

**Comment by sherryumlah** [comment]
Thanks for reaching out! Unfortunately, we no longer support this extension for Safari. I’m sorry about that! This is something we may revisit in the future, but for now, it’s not on our road map. The extension was still working in some older versions of Safari, so we left it active longer. I’m going to archive this repo to avoid confusion.    We do still support other [browser extensions](https://www.getharvest.com/integrations#browser-extensions) for Chrome, Firefox, and Edge, if these are helpful.

**Comment by Obbut** [comment]
@sherryumlah With macOS Big Sur, Safari now supports the WebExtensions API, using which Chrome extensions can be relatively easily converted to Safari extensions. It would be really great if this can get a little spot on your road map 😉 

https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by cusspvz** [comment]
@sherryumlah would be neat if you could support it. Safari works faster and uses fewer resources, including battery than Google Chrome. I suppose there are more people doing the transition due to the new M1 Macbook Pros. As @Obbut said, would be cool if you could put some effort into making the Chrome version compatible with Safari as well. I'm now using Chrome just to log time directly from GitHub since the macOS version doesn't allow us to tie an URL to an Entry.
